

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: desattir
  CLUSTER_NAME: desattir
  CLUSTER_RESOURCE_GROUP: desattir
  NAMESPACE: dotnetcore
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        printenv
        cat $GITHUB_EVENT_PATH
    
