on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ds-ms 
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker pull golang:latest
        docker tag golang:latest docker.pkg.github.com/ds-ms/dotnetcore-sample/app2:${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/ds-ms/dotnetcore-sample/app2:${{ secrets.GITHUB_TOKEN }}
  
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ds-ms 
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker pull golang:latest
        docker tag golang:latest docker.pkg.github.com/ds-ms/dotnetcore-sample/app2:${{ secrets.GITHUB_TOKEN }}-2
        docker push docker.pkg.github.com/ds-ms/dotnetcore-sample/app2:${{ secrets.GITHUB_TOKEN }}
